# For more information, see:
# https://github.com/actions/labeler

# Add 'analytics' label to any change to .analytics.effects.ts (or spec) files
analytics:
  - src/**/*.analytics.effects.ts
  - src/**/*.analytics.effects.spec.ts
  - src/app/providers/analytics/**/*.ts

# Add 'capacitor' label to any change to ios files & capacitor.config EXCEPT when exclusively the .plist file
capacitor:
  - capacitor.config.ts
  - ios/App/**/!(Info.plist)

# Add 'dependencies' label when package or lock file has changed
dependencies:
  - package.json
  - package-lock.json

# Add 'documentation' label when README.md changes
documentation:
  - README.md

# Add 'fastlane' label when any files inside fastlane change
fastlane:
  - fastlane/**/*

# Add 'tests' label when any .spec.ts changes
tests:
  - src/**/*.spec.ts

# Add 'typescript' label when any .ts changes
typescript:
  - src/**/*.ts

# Add 'version' label when .plist changes
version:
  - ios/App/App/Info.plist
