# For more information, see:
# https://github.com/actions/labeler

# Add 'capacitor' label to any change to ios files & capacitor.config EXCEPT for the .plist file
capacitor:
  - capacitor.config.ts
  - ios/App/**/!(Info.plist)

# Add 'dependencies' label when package or lock file has changed
dependencies:
  - package.json
  - package-lock.json

# Add 'documentation' label when README.md changes
documentation:
  - README.md

# Add 'fastlane' label when any files inside fastlane change
fastlane:
  - fastlane/**/*

# Add 'tests' label when any .spec.ts changes
tests:
  - src/**/*.spec.ts

# Add 'typescript' label when any .ts changes
typescript:
  - src/**/*.ts

# Add 'version' label when .plist changes
version:
  - ios/App/App/Info.plist
