# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Signs and builds the app with the DVSA production distribution certificate & provisioning profile"

  automatic_code_signing(
    path: "ios/App/App.xcodeproj",
    use_automatic_signing: false,
    profile_name: "Mobile Examiner App 2022",
    team_id: "K84TL26V3P",
    code_sign_identity: "iPhone Distribution: Vehicle and Operator Services Agency"
  )

  lane :build do
  	upgrade_super_old_xcode_project(
    	path: "ios/App/App.xcodeproj",
    	team_id: "K84TL26V3P"
  	)

  	update_project_team(
   		path: "ios/App/App.xcodeproj",
   		teamid: "K84TL26V3P"
   	)

  	update_code_signing_settings(
       path: "ios/App/App.xcodeproj",
       use_automatic_signing: false,
       team_id: "K84TL26V3P",
       code_sign_identity: "iPhone Distribution: Vehicle and Operator Services Agency",
       profile_name: "Mobile Examiner App 2022",
       targets: ".*App.*"
    )

	build_ios_app(
    	export_options: {
      		provisioningProfiles: {
        		"uk.gov.dvsa.drivingexaminerservices" => "DrivingExaminerServices",
      		}
    	},
   		workspace:  "ios/App/App.xcworkspace",
        	scheme: "App",
        	configuration: "Release",
        	output_directory: "build",
        	silent: false,
        	output_name: "DrivingExaminerService.ipa",
        	export_method: "enterprise",
        	codesigning_identity: "iPhone Distribution: Vehicle and Operator Services Agency"
   )
  end
end
