import * as moment from 'moment';
import { end2endPracticeSlotId } from '@shared/mocks/test-slot-ids.mock';

const todayAt8Am = moment().startOf('day').add(8, 'hour');

export const fakeJournalTestSlots = [
  {
    booking: {
      application: {
        applicationId: 1234532,
        bookingSequence: 7,
        checkDigit: 7,
        entitlementCheck: false,
        categoryEntitlementCheck: false,
        extendedTest: false,
        progressiveAccess: false,
        testCategory: 'B',
        vehicleGearbox: 'Manual',
        welshTest: false,
        specialNeedsCode: 'NONE',
        specialNeedsExtendedTest: false,
        meetingPlace: 'Next to test centre',
      },
      candidate: {
        candidateAddress: {
          addressLine1: '1 Hangar Lane',
          addressLine2: 'Someplace',
          addressLine3: 'Sometown',
          postcode: 'AB78 9CD',
        },
        candidateId: 107,
        candidateName: {
          firstName: 'Jeremy',
          lastName: 'Craig',
          title: 'Captain',
        },
        driverNumber: 'CRAIG375220A99HC',
        primaryTelephone: '01234 567890',
        emailAddress: 'captain@jeremy.com',
      },
    },
    slotDetail: {
      duration: 57,
      slotId: `${end2endPracticeSlotId}_0`,
      start: todayAt8Am.add(58, 'minutes').format(),
    },
    testCentre: {
      centreId: 54321,
      centreName: 'Example Test Centre',
      costCode: 'EXTC1',
    },
    vehicleSlotType: 'B57mins',
    vehicleSlotTypeCode: 7,
  },
  {
    booking: {
      application: {
        applicationId: 1234572,
        bookingSequence: 1,
        checkDigit: 3,
        entitlementCheck: false,
        specialNeedsCode: 'NONE',
        specialNeedsExtendedTest: false,
        extendedTest: false,
        progressiveAccess: false,
        testCategory: 'C',
        vehicleGearbox: 'Manual',
        vehicleHeight: 5,
        vehicleLength: 15,
        vehicleSeats: 50,
        vehicleWidth: 2,
        welshTest: false,
      },
      candidate: {
        candidateAddress: {
          addressLine1: 'The Gables Cottage',
          addressLine2: 'Home Farm',
          addressLine3: 'Farm Road',
          addressLine4: 'Farm Area',
          addressLine5: 'Farmtown',
          postcode: 'FA43 9XY',
        },
        candidateId: 106,
        candidateName: {
          firstName: 'James',
          lastName: 'Brown',
          title: 'Mr',
        },
        driverNumber: 'BROWN915220A99HC',
        gender: 'M',
        mobileTelephone: '07654 123456',
        primaryTelephone: '01234 567890',
        secondaryTelephone: '04321 098765',
        dateOfBirth: '1950-02-27',
        ethnicityCode: 'A',
      },
    },
    slotDetail: {
      duration: 57,
      slotId: `${end2endPracticeSlotId}_1`,
      start: '2022-01-20T13:35:00',
    },
    testCentre: {
      centreId: 54321,
      centreName: 'Example Test Centre',
      costCode: 'EXTC1',
    },
    vehicleTypeCode: 'C',
    vehicleSlotTypeCode: 7,
    examinerVisiting: false,
  },
  {
    booking: {
      application: {
        applicationId: 1234472,
        bookingSequence: 1,
        checkDigit: 3,
        entitlementCheck: false,
        specialNeedsCode: 'NONE',
        specialNeedsExtendedTest: false,
        extendedTest: false,
        progressiveAccess: false,
        testCategory: 'C1',
        vehicleGearbox: 'Manual',
        vehicleHeight: 5,
        vehicleLength: 15,
        vehicleSeats: 50,
        vehicleWidth: 2,
        welshTest: false,
      },
      candidate: {
        candidateAddress: {
          addressLine1: 'The Gables Cottage',
          addressLine2: 'Home Farm',
          addressLine3: 'Farm Road',
          addressLine4: 'Farm Area',
          addressLine5: 'Farmtown',
          postcode: 'FA43 9XY',
        },
        candidateId: 106,
        candidateName: {
          firstName: 'James',
          lastName: 'Brown',
          title: 'Mr',
        },
        driverNumber: 'BROWN915220A99HC',
        gender: 'M',
        mobileTelephone: '07654 123456',
        primaryTelephone: '01234 567890',
        secondaryTelephone: '04321 098765',
        dateOfBirth: '1950-02-27',
        ethnicityCode: 'A',
      },
    },
    slotDetail: {
      duration: 57,
      slotId: `${end2endPracticeSlotId}_2`,
      start: '2022-01-21T15:35:00',
    },
    testCentre: {
      centreId: 54321,
      centreName: 'Example Test Centre',
      costCode: 'EXTC1',
    },
    vehicleTypeCode: 'C',
    vehicleSlotTypeCode: 7,
    examinerVisiting: false,
  },
  {
    booking: {
      application: {
        applicationId: 1284472,
        bookingSequence: 1,
        checkDigit: 3,
        entitlementCheck: false,
        specialNeedsCode: 'NONE',
        specialNeedsExtendedTest: false,
        extendedTest: false,
        progressiveAccess: false,
        testCategory: 'C+E',
        vehicleGearbox: 'Manual',
        vehicleHeight: 5,
        vehicleLength: 15,
        vehicleSeats: 50,
        vehicleWidth: 2,
        welshTest: false,
      },
      candidate: {
        candidateAddress: {
          addressLine1: 'The Gables Cottage',
          addressLine2: 'Home Farm',
          addressLine3: 'Farm Road',
          addressLine4: 'Farm Area',
          addressLine5: 'Farmtown',
          postcode: 'FA43 9XY',
        },
        candidateId: 106,
        candidateName: {
          firstName: 'James',
          lastName: 'Brown',
          title: 'Mr',
        },
        driverNumber: 'BROWN915220A99HC',
        gender: 'M',
        mobileTelephone: '07654 123456',
        primaryTelephone: '01234 567890',
        secondaryTelephone: '04321 098765',
        dateOfBirth: '1950-02-27',
        ethnicityCode: 'A',
      },
    },
    slotDetail: {
      duration: 57,
      slotId: `${end2endPracticeSlotId}_3`,
      start: '2022-01-21T17:35:00',
    },
    testCentre: {
      centreId: 54321,
      centreName: 'Example Test Centre',
      costCode: 'EXTC1',
    },
    vehicleTypeCode: 'C',
    vehicleSlotTypeCode: 7,
    examinerVisiting: false,
  },
  {
    booking: {
      application: {
        applicationId: 1237472,
        bookingSequence: 1,
        checkDigit: 3,
        entitlementCheck: false,
        specialNeedsCode: 'NONE',
        specialNeedsExtendedTest: false,
        extendedTest: false,
        progressiveAccess: false,
        testCategory: 'C1+E',
        vehicleGearbox: 'Manual',
        vehicleHeight: 5,
        vehicleLength: 15,
        vehicleSeats: 50,
        vehicleWidth: 2,
        welshTest: false,
      },
      candidate: {
        candidateAddress: {
          addressLine1: 'The Gables Cottage',
          addressLine2: 'Home Farm',
          addressLine3: 'Farm Road',
          addressLine4: 'Farm Area',
          addressLine5: 'Farmtown',
          postcode: 'FA43 9XY',
        },
        candidateId: 106,
        candidateName: {
          firstName: 'James',
          lastName: 'Brown',
          title: 'Mr',
        },
        driverNumber: 'BROWN915220A99HC',
        gender: 'M',
        mobileTelephone: '07654 123456',
        primaryTelephone: '01234 567890',
        secondaryTelephone: '04321 098765',
        dateOfBirth: '1950-02-27',
        ethnicityCode: 'A',
      },
    },
    slotDetail: {
      duration: 57,
      slotId: `${end2endPracticeSlotId}_4`,
      start: '2022-01-21T16:35:00',
    },
    testCentre: {
      centreId: 54321,
      centreName: 'Example Test Centre',
      costCode: 'EXTC1',
    },
    vehicleTypeCode: 'C',
    vehicleSlotTypeCode: 7,
    examinerVisiting: false,
  },
];
