import { TestCategory } from '@dvsa/mes-test-schema/category-definitions/common/test-category';

export const vehicleDetails = {
  [TestCategory.A]: false,
  [TestCategory.A1]: false,
  [TestCategory.A2]: false,
  [TestCategory.ADI2]: false,
  [TestCategory.ADI3]: false,
  [TestCategory.AM]: false,
  [TestCategory.B]: false,
  [TestCategory.B1]: false,
  [TestCategory.BE]: true,
  [TestCategory.C]: true,
  [TestCategory.CM]: true,
  [TestCategory.C1]: true,
  [TestCategory.C1M]: true,
  [TestCategory.C1E]: true,
  [TestCategory.C1EM]: true,
  [TestCategory.CCPC]: false,
  [TestCategory.CE]: true,
  [TestCategory.CEM]: true,
  [TestCategory.D]: true,
  [TestCategory.DM]: true,
  [TestCategory.D1]: true,
  [TestCategory.D1M]: true,
  [TestCategory.D1E]: true,
  [TestCategory.D1EM]: true,
  [TestCategory.DCPC]: false,
  [TestCategory.DE]: true,
  [TestCategory.DEM]: true,
  [TestCategory.EUA1M1]: false,
  [TestCategory.EUA1M2]: false,
  [TestCategory.EUA2M1]: false,
  [TestCategory.EUA2M2]: false,
  [TestCategory.EUAM1]: false,
  [TestCategory.EUAM2]: false,
  [TestCategory.EUAMM1]: false,
  [TestCategory.EUAMM2]: false,
  [TestCategory.F]: false,
  [TestCategory.G]: false,
  [TestCategory.H]: false,
  [TestCategory.K]: false,
  [TestCategory.SC]: false,
};
