#!/bin/sh
# Removes deprecated netinet6/in6.h import from CDVReachability.m
# This file is regenerated by Capacitor on each build, so this patch must run post-build.
sed -i '' '/#import <netinet6\/in6.h>/d' ios/capacitor-cordova-ios-plugins/sources/CordovaPluginNetworkInformation/CDVReachability.m

