#!/bin/sh
# Removes deprecated netinet6/in6.h import from CDVReachability.m
# This file is regenerated by Capacitor on each build, so this patch must run post-build.
TARGET_FILE="ios/capacitor-cordova-ios-plugins/sources/CordovaPluginNetworkInformation/CDVReachability.m"

if [ ! -f "$TARGET_FILE" ]; then
  echo "Error: Expected generated Capacitor plugin file not found: $TARGET_FILE" >&2
  echo "Run this script after Capacitor has generated iOS plugin sources, or update the path if the generated layout has changed." >&2
  exit 1
fi

sed -i '' '/#import <netinet6\/in6.h>/d' "$TARGET_FILE"

