name: 📱 Build Mobile Artefact 2
run-name: "📱 ${{ github.actor}} - ${{ github.ref_name }} - ${{ github.run_id }}"

on:
  push:
    branches: [ 'feature/MES-10346' ]

env:
  ENVIRONMENT: feature
  GEM_HOME: $HOME/des/.gem
  AWS_DEFAULT_REGION: ${{ vars.DVSA_AWS_REGION }}

permissions:
  id-token: write
  contents: write

jobs:
  build:
    name: 📱 Build Mobile App
    runs-on: mito-6
    steps:
      - name: 📨 Checkout
        uses: actions/checkout@v4

      - name: 🚀 Setup Paths
        run: echo "/opt/homebrew/bin:/opt/homebrew/sbin:$HOME/.rbenv/shims:${{ env.GEM_HOME }}/bin" >> $GITHUB_PATH

      - name: 🔍 Read .nvmrc
        id: nvm
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_OUTPUT

      - name: ⚙️ Setup Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: 🔑 Configure AWS Connection
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DES_AWS_ROLE }}
          aws-region: ${{ vars.DVSA_AWS_REGION }}
          role-session-name: mobile-build-${{ github.repository_id }}

      - name: 🤫 Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            des-mobile-app/env
            des-globals/env
          parse-json-secrets: true

      - name: ⚙️ Set Fastlane Configuration Files
        run: aws secretsmanager get-secret-value --secret-id des-mobile-app/fastlane-config --query SecretString --output text | bash

      - name: ⚙️ Set Configuration Files
        env:
          IONIC_TOKEN: ${{ env.DES_MOBILE_APP_ENV_IONIC_TOKEN }}
          DVSA_PACKAGE_TOKEN: ${{ env.DES_MOBILE_APP_ENV_DVSA_PACKAGE_TOKEN }}
          IONIC_PRODUCT_KEY: ${{ env.DES_MOBILE_APP_ENV_IONIC_PRODUCT_KEY }}
          IONIC_APP_ID: ${{ env.DES_MOBILE_APP_ENV_IONIC_APP_ID }}
          IONIC_ORG_ID: ${{ env.DES_MOBILE_APP_ENV_IONIC_ORG_ID }}
        run: aws secretsmanager get-secret-value --secret-id des-mobile-app/build-config --query SecretString --output text | bash

      - name: ➕ Install Dependencies
        run: |
          npm ci
          bundle config set path ${{ env.GEM_HOME }}
          bundle install --jobs $(sysctl -n hw.physicalcpu)

      - name: ⚒️ Build Project
        run: |
          npm run config:dev
          npm run schema-version
          npm run build:qr

      - name: 🛠️ Build Mobile
        env:
          UPLOAD_PATH: ${{ env.ENVIRONMENT }}
        run: |
          bundle exec fastlane build_ipa

      - name: 🔪 Kill Xcode
        if: always()
        run: osascript -e 'quit app "Xcode"'
