name: 📱 Build Mobile Artefact
run-name: "📱 ${{ github.ref_name }} - ${{ github.run_id }}"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    tags:
      - release-*

permissions:
  id-token: write
  contents: write

jobs:
  develop:
    # if: github.event_name == 'push' && startsWith(github.ref_name, 'develop')
    uses: dvsa/des-workflow-actions/.github/workflows/build-mobile-app.yaml@MES-10614-mobile-app-fastlane-updates
    with:
      runs-on: 'MACOS-ARM64'
      environment: develop
      config-type: test
      build-simulator: true
      build-ipa: true
      upload_path: develop
    secrets:
      AWS_ROLE: ${{ secrets.DES_AWS_ROLE }}

#  feature:
#    if: github.event_name == 'workflow_dispatch'
#    uses: dvsa/des-workflow-actions/.github/workflows/build-mobile-app.yaml@main
#    with:
#      runs-on: 'MACOS-ARM64'
#      environment: feature
#      config-type: dev
#      build-type: qr
#      build-simulator: true
#      build-ipa: true
#      upload_path: feature
#    secrets:
#      AWS_ROLE: ${{ secrets.DES_AWS_ROLE }}
#
#  release:
#    if: github.event_name == 'push' && startsWith(github.ref_name, 'release-')
#    uses: dvsa/des-workflow-actions/.github/workflows/build-mobile-app.yaml@main
#    with:
#      runs-on: 'MACOS-ARM64'
#      environment: release
#      config-type: dev
#      build-type: prod
#      build-ipa: true
#      upload_path: release
#    secrets:
#      AWS_ROLE: ${{ secrets.DES_AWS_ROLE }}
