name: 📱 Build Mobile Artefact
run-name: "📱 ${{ github.ref_name }} - ${{ github.run_id }}"

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'For debugging specify the runner (defaults to the group: MACOS-ARM64)'
        required: false
        default: 'MACOS-ARM64'
        type: choice
        options:
          - 'MACOS-ARM64'
  push:
    branches:
      - develop
      - mes-*
    tags:
      - release-*

permissions:
  id-token: write
  contents: write

jobs:
  develop:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'develop')
    uses: dvsa/des-workflow-actions/.github/workflows/build-mobile-app.yaml@main
    with:
      runs-on: 'MACOS-ARM64'
      environment: develop
      config-type: test
      build-simulator: true
      build-ipa: false
      upload_path: develop
    secrets:
      AWS_ROLE: ${{ secrets.DES_AWS_ROLE }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  feature:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref_name, 'mes-'))
    uses: dvsa/des-workflow-actions/.github/workflows/build-mobile-app.yaml@main
    with:
      runs-on: ${{ inputs.runner }}
      environment: feature
      config-type: test
      build-simulator: true
      build-ipa: false
      upload_path: feature
    secrets:
      AWS_ROLE: ${{ secrets.DES_AWS_ROLE }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  qr:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.ref_name, 'mes-'))
    uses: dvsa/des-workflow-actions/.github/workflows/build-mobile-app.yaml@main
    with:
      runs-on: ${{ inputs.runner }}
      environment: feature
      config-type: dev
      build-type: qr
      build-ipa: true
      upload_path: feature
    secrets:
      AWS_ROLE: ${{ secrets.DES_AWS_ROLE }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

  release:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'release-')
    uses: dvsa/des-workflow-actions/.github/workflows/build-mobile-app.yaml@main
    with:
      runs-on: 'MACOS-ARM64'
      environment: prod
      config-type: dev
      build-type: prod
      build-ipa: true
      upload_path: release
    secrets:
      AWS_ROLE: ${{ secrets.DES_AWS_ROLE }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
