#name: ESLint
#on: push
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install modules
#        run: npm i
#      - name: Run ESLint
#        run: eslint . --ext .ts


name: DES Continuous Integration

on:
  pull_request:
    branches: [ develop ]

jobs:
  lint_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
